import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, CalendarDays, Check, ExternalLink, FileSpreadsheet, FolderOpen, History, Mail, MoreHorizontal, RefreshCw, Search, Send, SlidersHorizontal, Upload, X } from 'lucide-react';
import { EmailStatusBadge } from './billing-ui';
import { F29MailComposer } from './F29MailComposer';
import { F29_STATUS_LABELS, type ClientRow, type F29StatusCode } from './types';
import { DriveAuthorizationError, loadF29PeriodDocument, scanClientDrive, uploadF29Excel } from './client-api';
import { connectGoogleDrive } from './supabase';
import { ContextualTooltip } from './HelpSystem';

const MONTHS = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const money = new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 });
const responsibleTone: Record<string, string> = {
  GABRIELA: 'responsible-gabriela', 'ALE CANDIA': 'responsible-ale', PAOLA: 'responsible-paola', MARCELA: 'responsible-marcela',
  ANDREA: 'responsible-andrea', TANIA: 'responsible-tania', LAURA: 'responsible-laura', SCARLEN: 'responsible-scarlen',
};
const statusTone: Record<F29StatusCode, string> = { A: 'is-ready', B: 'is-blocked', C: 'is-declared', D: 'is-paid', E: 'is-pending', F: 'is-neutral', G: 'is-pending', H: 'is-blocked' };

function CommitInput({ value, className, label, type = 'text', onCommit }: { value: string | number | null; className: string; label: string; type?: string; onCommit: (value: string) => void }) {
  const [draft, setDraft] = useState(value ?? '');
  const [focused, setFocused] = useState(false);
  const isMoney = className.includes('inline-number');
  useEffect(() => setDraft(value ?? ''), [value]);
  const display = isMoney && !focused && draft !== '' ? money.format(Number(draft)) : draft;
  return <input className={className} aria-label={label} type={isMoney ? 'text' : type} value={display} onFocus={() => setFocused(true)} onChange={event => setDraft(isMoney ? event.target.value.replace(/[^0-9-]/g, '') : event.target.value)} onBlur={() => { setFocused(false); if (String(draft) !== String(value ?? '')) onCommit(String(draft)); }} onKeyDown={event => { if (event.key === 'Enter') event.currentTarget.blur(); }} />;
}

function SaveState({ state }: { state?: 'saving' | 'saved' | 'error' }) {
  if (state === 'saving') return <span className="save-state saving">Guardando…</span>;
  if (state === 'error') return <span className="save-state error"><AlertTriangle size={12} /> Error</span>;
  if (state === 'saved') return <span className="save-state saved"><Check size={12} /> Guardado</span>;
  return <span className="save-state">—</span>;
}

function PriorAmount({ current, previous }: { current: number | null; previous: number | null }) {
  if (previous === null) return <span className="amount-comparison"><strong>—</strong><small>Sin período anterior</small></span>;
  const delta = current === null ? null : current - previous;
  return <span className="amount-comparison"><strong>{money.format(previous)}</strong>{delta !== null && <small className={delta > 0 ? 'up' : delta < 0 ? 'down' : ''}>{delta > 0 ? '▲ ' : delta < 0 ? '▼ ' : '＝ '}{money.format(Math.abs(delta))}</small>}</span>;
}

function F29DocumentCell({ row, document, state, onReload, onUpload }: { row: ClientRow; document: ClientRow['f29Document']; state?: { status: 'loading' | 'success' | 'error'; message: string; authorize?: boolean }; onReload: () => void; onUpload: (file?: File) => void }) {
  return <div className="f29-document-cell">{document ? <a href={document.url ?? '#'} target={document.url ? '_blank' : undefined} rel="noreferrer" title={document.name}><FileSpreadsheet size={14}/><span>{document.name}</span>{document.url && <ExternalLink size={12}/>}</a> : <div className="f29-document-actions"><button disabled={state?.status === 'loading' || !row.driveFolderId} onClick={onReload}><RefreshCw size={12}/> Recargar mes</button><label><Upload size={12}/> Subir<input type="file" accept=".xls,.xlsx,.xlsm,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event => { onUpload(event.target.files?.[0]); event.currentTarget.value = ''; }}/></label></div>}{state && <small className={state.status}>{state.message}{state.authorize && <button onClick={() => void connectGoogleDrive()}> Autorizar</button>}</small>}</div>;
}

export function F29OperationsDashboard({ rows, updateRow, openClient, year, month, navigatePeriod, saveStates, reload, isAdmin }: { rows: ClientRow[]; updateRow: (id: string, patch: Partial<ClientRow>) => Promise<void>; openClient: (row: ClientRow) => void; year: number; month: number; navigatePeriod: (year: number, month: number) => void; saveStates: Record<string, 'saving' | 'saved' | 'error'>; reload: () => Promise<void>; isAdmin: boolean }) {
  const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState('all'); const [responsible, setResponsible] = useState('all'); const [operationFilter, setOperationFilter] = useState('all'); const [onlyObserved, setOnlyObserved] = useState(false); const [filtersOpen, setFiltersOpen] = useState(false); const [page, setPage] = useState(1); const [emailRow, setEmailRow] = useState<ClientRow | null>(null); const [reminderRow, setReminderRow] = useState<ClientRow | null>(null);
  const [documentOverrides, setDocumentOverrides] = useState<Record<string, ClientRow['f29Document']>>({});
  const [documentState, setDocumentState] = useState<Record<string, { status: 'loading' | 'success' | 'error'; message: string; authorize?: boolean }>>({});
  const [inspectorId, setInspectorId] = useState<string | null>(null);
  const [inspectorTab, setInspectorTab] = useState<'summary' | 'documents' | 'history' | 'activity'>('summary');
  const documentFor = (row: ClientRow) => Object.prototype.hasOwnProperty.call(documentOverrides, row.id) ? documentOverrides[row.id] : row.f29Document;
  const reloadDocument = async (row: ClientRow) => { setDocumentState(current => ({ ...current, [row.id]: { status: 'loading', message: 'Revisando carpeta…' } })); try { await scanClientDrive(row.id, { year, month }); const document = await loadF29PeriodDocument(row.id, year, month); setDocumentOverrides(current => ({ ...current, [row.id]: document })); setDocumentState(current => ({ ...current, [row.id]: { status: 'success', message: document ? 'Excel encontrado.' : 'Carpeta revisada; no hay Excel.' } })); } catch (error) { setDocumentState(current => ({ ...current, [row.id]: { status: 'error', message: error instanceof Error ? error.message : 'No fue posible revisar la carpeta.', authorize: error instanceof DriveAuthorizationError } })); } };
  const uploadDocument = async (row: ClientRow, file?: File) => { if (!file) return; setDocumentState(current => ({ ...current, [row.id]: { status: 'loading', message: 'Subiendo Excel…' } })); try { const result = await uploadF29Excel(row.id, year, month, file); setDocumentOverrides(current => ({ ...current, [row.id]: result.document })); setDocumentState(current => ({ ...current, [row.id]: { status: 'success', message: 'Excel subido e indexado.' } })); } catch (error) { setDocumentState(current => ({ ...current, [row.id]: { status: 'error', message: error instanceof Error ? error.message : 'No fue posible subir el Excel.', authorize: error instanceof DriveAuthorizationError } })); } };
  const pageSize = 100;
  const responsibles = [...new Set(rows.map(row => row.accountant).filter(Boolean))].sort();
  useEffect(() => setPage(1), [query, statusFilter, responsible, operationFilter, onlyObserved, year, month]);
  const filtered = useMemo(() => rows.filter(row =>
    `${row.rut} ${row.name} ${row.accountingCode ?? ''}`.toLowerCase().includes(query.trim().toLowerCase()) &&
    (statusFilter === 'all' || (statusFilter === 'missing' ? !row.periodId : row.statusCode === statusFilter)) &&
    (responsible === 'all' || row.accountant === responsible) && (!onlyObserved || Boolean(row.observation.trim())) &&
    (operationFilter === 'all' || (operationFilter === 'email' && row.emailStatus !== 'sent') || (operationFilter === 'unpaid' && !row.taxPaid && (row.amount ?? 0) > 0) || (operationFilter === 'paid' && row.taxPaid) || (operationFilter === 'reminded' && Boolean(row.taxLastReminderAt)))
  ), [rows, query, statusFilter, responsible, onlyObserved, operationFilter]);
  const shown = filtered.slice((page - 1) * pageSize, page * pageSize); const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize));
  const periods = rows.filter(row => row.periodId); const loaded = periods.filter(row => row.statusCode === 'A').length; const sent = periods.filter(row => row.emailStatus === 'sent' || row.statusCode === 'C' || row.statusCode === 'D').length; const paid = periods.filter(row => row.taxPaid || row.statusCode === 'D').length; const pending = rows.length - paid;
  const inspectorRow = inspectorId ? rows.find(row => row.id === inspectorId) ?? null : null;
  const selectInspector = (row: ClientRow) => { setInspectorId(row.id); setInspectorTab('summary'); };
  return <div className={`f29-command-layout ${inspectorRow ? 'has-inspector' : ''}`}><div className="control-content wide-content"><div className="control-page-head"><div><span>Operación mensual</span><h1>F29 <i>/</i> Operaciones</h1><p>{MONTHS[month - 1]} {year} · control de declaraciones, comunicaciones y pago.</p></div><div className="page-actions period-controls"><select aria-label="Mes F29" value={month} onChange={event => navigatePeriod(year, Number(event.target.value))}>{MONTHS.map((name,index) => <option value={index + 1} key={name}>{name}</option>)}</select><select aria-label="Año F29" value={year} onChange={event => navigatePeriod(Number(event.target.value), month)}>{[2025,2026,2027].map(value => <option key={value}>{value}</option>)}</select></div></div>
    <div className="f29-ops-kpis" data-help="f29-kpis"><div><span>Clientes</span><strong>{rows.length}</strong></div><div><span>Cargadas</span><strong>{loaded}</strong></div><div><span>Informadas / Mail enviado</span><strong>{sent}</strong></div><div><span>Pagadas</span><strong>{paid}</strong></div><div><span>Pendientes <ContextualTooltip label="Qué significa pendiente">Cliente sin pago F29 registrado para el período.</ContextualTooltip></span><strong className={pending ? 'negative' : ''}>{pending}</strong></div></div>
    <section className="operations-card"><div className="table-toolbar f29-toolbar"><div className="toolbar-search"><Search size={16} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar RUT, razón social o Conta…" /></div><button className={`mobile-filter-toggle ${filtersOpen?'active':''}`} onClick={()=>setFiltersOpen(value=>!value)}><SlidersHorizontal size={14}/>Filtros{[statusFilter!=='all',responsible!=='all',operationFilter!=='all',onlyObserved].filter(Boolean).length>0&&<b>{[statusFilter!=='all',responsible!=='all',operationFilter!=='all',onlyObserved].filter(Boolean).length}</b>}</button><div className={`mobile-filter-strip ${filtersOpen?'is-open':''}`}><select value={statusFilter} onChange={event => setStatusFilter(event.target.value)} aria-label="Estado F29"><option value="all">Todos los estados</option><option value="missing">Sin período</option>{Object.entries(F29_STATUS_LABELS).map(([code,label]) => <option value={code} key={code}>{label}</option>)}</select><select value={responsible} onChange={event => setResponsible(event.target.value)} aria-label="Responsable"><option value="all">Todos</option>{responsibles.map(name => <option key={name}>{name}</option>)}</select><select value={operationFilter} onChange={event => setOperationFilter(event.target.value)} aria-label="Comunicación y pago"><option value="all">Email y pago: todos</option><option value="email">Email no enviado</option><option value="unpaid">Pago F29 pendiente</option><option value="paid">Pago F29 realizado</option><option value="reminded">Con recordatorio</option></select><button className={`filter-button ${onlyObserved ? 'active' : ''}`} onClick={() => setOnlyObserved(value => !value)}><SlidersHorizontal size={15} /> Con observación</button></div></div>
      <div className="table-scroll command-table-scroll"><table className="ops-table f29-command-table"><thead><tr><th>Cliente</th><th>Responsable</th><th>Estado F29</th><th>Pago</th><th>Monto</th><th>Alertas</th><th aria-label="Acciones"/></tr></thead><tbody>{shown.map(row => <tr key={`command-${row.id}`} className={`${inspectorId===row.id?'is-selected ':''}${!row.periodId?'missing-period-row':''}`} onClick={()=>selectInspector(row)}><td><span className="command-client"><strong>{row.name}</strong><small>{row.rut}{row.accountingCode?` · Conta ${row.accountingCode}`:''}</small></span></td><td><span className="command-responsible"><span className="avatar">{row.initials}</span>{row.accountant}</span></td><td><span className={`status-pill ${row.statusCode ? statusTone[row.statusCode] : 'is-neutral'}`}><i/>{row.statusLabel||'Sin estado'}</span></td><td><span className={`status-pill ${row.taxPaid?'is-paid':(row.amount??0)>0?'is-pending':'is-neutral'}`}><i/>{row.taxPaid?'Pagado':(row.amount??0)>0?'Pendiente':'Sin pago'}</span></td><td className="command-amount">{row.amount===null?'—':money.format(row.amount)}</td><td>{row.observation?<span className="command-alert" title={row.observation}><AlertTriangle size={13}/>{row.observation}</span>:<span className="command-empty">—</span>}</td><td><button className="command-action" aria-label={`Inspeccionar ${row.name}`} onClick={event=>{event.stopPropagation();selectInspector(row)}}><MoreHorizontal size={16}/></button></td></tr>)}</tbody></table></div>
      <div className="f29-mobile-list" aria-label="Clientes F29">{shown.map(row => <article className={`f29-mobile-card ${!row.periodId ? 'missing-period-row' : ''}`} key={`mobile-${row.id}`}><button className="mobile-record-open" onClick={()=>selectInspector(row)}><span className="mobile-record-head"><span><strong>{row.name}</strong><small>{row.rut} · {row.accountant}</small></span><span className={`status-pill ${row.statusCode ? statusTone[row.statusCode] : 'is-neutral'}`}><i/>{row.statusLabel||'Sin estado'}</span></span><span className="mobile-record-bottom"><strong>{row.amount===null?'—':money.format(row.amount)}</strong><span className={row.taxPaid?'paid':'pending'}><i/>{row.taxPaid?'Pagado':(row.amount??0)>0?'Pendiente':'Sin pago'}</span><span>{row.emailStatus==='sent'?'Email enviado':'Email pendiente'}</span></span>{row.observation&&<span className="mobile-record-alert"><AlertTriangle size={12}/>{row.observation}</span>}</button></article>)}</div>
      <footer className="table-footer"><span>Mostrando {shown.length} de {filtered.length} clientes</span><span className="pagination"><button disabled={page === 1} onClick={() => setPage(value => value - 1)}>Anterior</button><b>{page} / {pageCount}</b><button disabled={page === pageCount} onClick={() => setPage(value => value + 1)}>Siguiente</button></span></footer></section>
    {emailRow && <F29MailComposer row={emailRow} onClose={() => setEmailRow(null)} onSent={reload} />}{reminderRow && <F29MailComposer row={reminderRow} mode="tax-reminder" onClose={() => setReminderRow(null)} onSent={reload} />}
  </div>{inspectorRow&&<aside className="operation-inspector" aria-label={`Inspector de ${inspectorRow.name}`}><header><div><span>Cliente F29</span><h2>{inspectorRow.name}</h2><small>{inspectorRow.rut}{inspectorRow.accountingCode?` · Conta ${inspectorRow.accountingCode}`:''}</small></div><button aria-label="Cerrar inspector" onClick={()=>setInspectorId(null)}><X size={18}/></button></header><nav className="inspector-tabs" aria-label="Secciones del inspector"><button className={inspectorTab==='summary'?'active':''} onClick={()=>setInspectorTab('summary')}>Resumen</button><button className={inspectorTab==='documents'?'active':''} onClick={()=>setInspectorTab('documents')}>Documentos</button><button className={inspectorTab==='history'?'active':''} onClick={()=>setInspectorTab('history')}>Historial</button><button className={inspectorTab==='activity'?'active':''} onClick={()=>setInspectorTab('activity')}>Actividad</button></nav><div className="inspector-scroll">
    {inspectorTab==='summary'&&<><section className="inspector-status"><span className={`status-pill ${inspectorRow.statusCode?statusTone[inspectorRow.statusCode]:'is-neutral'}`}><i/>{inspectorRow.statusLabel||'Sin estado'}</span><SaveState state={saveStates[inspectorRow.id]}/></section><section className="inspector-fields"><label>Responsable<select className={`inline-select responsible-select ${responsibleTone[inspectorRow.accountant.toUpperCase()]??'responsible-default'}`} value={inspectorRow.accountant} onChange={event=>void updateRow(inspectorRow.id,{accountant:event.target.value})}>{responsibles.map(name=><option key={name}>{name}</option>)}</select></label><label>Monto F29<CommitInput className="inline-number" label={`Monto F29 de ${inspectorRow.name}`} value={inspectorRow.amount} onCommit={value=>void updateRow(inspectorRow.id,{amount:value?Number(value):null})}/></label><label>Estado F29<select className={`inline-status ${inspectorRow.statusCode?statusTone[inspectorRow.statusCode]:'is-neutral'}`} value={inspectorRow.statusCode??''} onChange={event=>{const code=event.target.value as F29StatusCode;void updateRow(inspectorRow.id,{statusCode:code,statusLabel:F29_STATUS_LABELS[code]})}}><option value="">Sin estado</option>{Object.entries(F29_STATUS_LABELS).map(([code,label])=><option value={code} key={code}>{label}</option>)}</select></label><label>Fecha<input className="inline-date" type="date" value={inspectorRow.filedDate??''} onChange={event=>void updateRow(inspectorRow.id,{filedDate:event.target.value||null})}/></label></section>{inspectorRow.observation&&<section className="inspector-alert"><AlertTriangle size={15}/><span><strong>Alerta operativa</strong>{inspectorRow.observation}</span></section>}<section className="inspector-section"><h3>Acciones rápidas</h3><div className="inspector-actions"><button disabled={!inspectorRow.periodId} onClick={()=>setEmailRow(inspectorRow)}><Mail size={15}/>Enviar F29</button><button disabled={(inspectorRow.amount??0)<=0||inspectorRow.taxPaid} onClick={()=>setReminderRow(inspectorRow)}><Send size={15}/>Recordar pago</button><button onClick={()=>openClient(inspectorRow)}><MoreHorizontal size={15}/>Ficha completa</button></div></section><section className="inspector-section"><h3>Contacto</h3><dl><div><dt>Email</dt><dd>{inspectorRow.legalRepresentativeEmail||'No informado'}</dd></div><div><dt>Teléfono</dt><dd>{inspectorRow.phone||'No informado'}</dd></div></dl></section><section className="inspector-section"><h3>Nota interna</h3>{isAdmin?<CommitInput className="inline-note inspector-note" label={`Observación de ${inspectorRow.name}`} value={inspectorRow.observation} onCommit={value=>void updateRow(inspectorRow.id,{observation:value})}/>:<p>{inspectorRow.observation||'Sin observaciones.'}</p>}</section></>}
    {inspectorTab==='documents'&&<section className="inspector-section inspector-tab-panel"><FolderOpen size={20}/><h3>Documento del período</h3><F29DocumentCell row={inspectorRow} document={documentFor(inspectorRow)} state={documentState[inspectorRow.id]} onReload={()=>void reloadDocument(inspectorRow)} onUpload={file=>void uploadDocument(inspectorRow,file)}/></section>}
    {inspectorTab==='history'&&<section className="inspector-section inspector-tab-panel"><History size={20}/><h3>Contexto del período</h3><dl><div><dt>Monto anterior</dt><dd>{inspectorRow.previousAmount===null?'—':money.format(inspectorRow.previousAmount)}</dd></div><div><dt>Último recordatorio</dt><dd>{inspectorRow.taxLastReminderAt?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium'}).format(new Date(inspectorRow.taxLastReminderAt)):'Sin envíos'}</dd></div><div><dt>Actualización</dt><dd>{inspectorRow.updated}</dd></div></dl></section>}
    {inspectorTab==='activity'&&<section className="inspector-section inspector-tab-panel"><Activity size={20}/><h3>Actividad reciente</h3><p>Los cambios de estado, correos y pagos quedan registrados en la trazabilidad del cliente.</p><button className="button-ghost" onClick={()=>openClient(inspectorRow)}>Abrir actividad completa</button></section>}
  </div></aside>}</div>;
}
