import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, CalendarDays, Check, ExternalLink, FileSpreadsheet, FolderOpen, History, Mail, MoreHorizontal, RefreshCw, Search, Send, SlidersHorizontal, Upload, X } from 'lucide-react';
import { EmailStatusBadge } from './billing-ui';
import { F29MailComposer } from './F29MailComposer';
import { F29_STATUS_LABELS, type ClientRow, type F29StatusCode } from './types';
import { DriveAuthorizationError, loadF29PeriodDocument, markF29Payment, scanClientDrive, sendF29AdminReview, uploadF29Excel } from './client-api';
import { connectGoogleDrive } from './supabase';
import { ContextualTooltip } from './HelpSystem';
import { matchesF29Workflow, type F29WorkflowFilter } from './operational-utils';
import { compareSortValues, MultiSelectFilter, nextSort, SortableHeader, type SortState } from './list-controls';

const MONTHS = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const money = new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 });
const responsibleTone: Record<string, string> = {
  GABRIELA: 'responsible-gabriela', 'ALE CANDIA': 'responsible-ale', PAOLA: 'responsible-paola', MARCELA: 'responsible-marcela',
  ANDREA: 'responsible-andrea', TANIA: 'responsible-tania', LAURA: 'responsible-laura', SCARLEN: 'responsible-scarlen',
};
const statusTone: Record<F29StatusCode, string> = { A: 'is-ready', B: 'is-blocked', C: 'is-declared', D: 'is-paid', E: 'is-pending', F: 'is-neutral', G: 'is-pending', H: 'is-blocked' };
type F29SortKey = 'client' | 'responsible' | 'status' | 'payment' | 'amount' | 'alerts';
const workflowOptions: { value: F29WorkflowFilter; label: string }[] = [
  { value: 'pending', label: 'Pendientes · trabajo abierto' }, { value: 'loaded', label: 'Cargadas' },
  { value: 'review', label: 'Pendiente revisión' }, { value: 'informed_unpaid', label: 'Informadas no pagadas' },
  { value: 'overdue', label: 'Vencidas / pago pendiente' },
  { value: 'informed', label: 'Informadas' }, { value: 'paid', label: 'Pagadas' },
  { value: 'issues', label: 'Con incidencias' }, { value: 'postponed', label: 'Postergadas' },
  { value: 'missing', label: 'Sin estado' }, { value: 'no_movement', label: 'Sin movimiento' },
];
const operationOptions = [
  { value: 'email', label: 'Email no enviado' }, { value: 'unpaid', label: 'Pago F29 pendiente' },
  { value: 'paid', label: 'Pago F29 realizado' }, { value: 'reminded', label: 'Con recordatorio' },
];
const isF29Alert = (row: ClientRow) => Boolean(row.observation.trim()) || ['B', 'E', 'G', 'H'].includes(row.statusCode ?? '') || Boolean(row.taxPaymentDueDate && !row.taxPaid && row.taxPaymentDueDate < new Date().toISOString().slice(0, 10));

function CommitInput({ value, className, label, type = 'text', onCommit }: { value: string | number | null; className: string; label: string; type?: string; onCommit: (value: string) => void }) {
  const [draft, setDraft] = useState(value ?? '');
  const [focused, setFocused] = useState(false);
  const isMoney = className.includes('inline-number');
  useEffect(() => setDraft(value ?? ''), [value]);
  const display = isMoney && !focused && draft !== '' ? money.format(Number(draft)) : draft;
  return <input className={className} aria-label={label} type={isMoney ? 'text' : type} value={display} onFocus={() => setFocused(true)} onChange={event => setDraft(isMoney ? event.target.value.replace(/[^0-9-]/g, '') : event.target.value)} onBlur={() => { setFocused(false); if (String(draft) !== String(value ?? '')) onCommit(String(draft)); }} onKeyDown={event => { if (event.key === 'Enter') event.currentTarget.blur(); }} />;
}

function SaveState({ state }: { state?: 'saving' | 'saved' | 'error' }) {
  if (state === 'saving') return <span className="save-state saving">Guardando…</span>;
  if (state === 'error') return <span className="save-state error"><AlertTriangle size={12} /> Error</span>;
  if (state === 'saved') return <span className="save-state saved"><Check size={12} /> Guardado</span>;
  return <span className="save-state">—</span>;
}

function PriorAmount({ current, previous }: { current: number | null; previous: number | null }) {
  if (previous === null) return <span className="amount-comparison"><strong>—</strong><small>Sin período anterior</small></span>;
  const delta = current === null ? null : current - previous;
  return <span className="amount-comparison"><strong>{money.format(previous)}</strong>{delta !== null && <small className={delta > 0 ? 'up' : delta < 0 ? 'down' : ''}>{delta > 0 ? '▲ ' : delta < 0 ? '▼ ' : '＝ '}{money.format(Math.abs(delta))}</small>}</span>;
}

function F29DocumentCell({ row, document, state, onReload, onUpload }: { row: ClientRow; document: ClientRow['f29Document']; state?: { status: 'loading' | 'success' | 'error'; message: string; authorize?: boolean }; onReload: () => void; onUpload: (file?: File) => void }) {
  const expectsDocument = ['A', 'C', 'D'].includes(row.statusCode ?? '');
  return <div className="f29-document-cell">{document ? <a href={document.url ?? '#'} target={document.url ? '_blank' : undefined} rel="noreferrer" title={document.name}><FileSpreadsheet size={14}/><span>{document.name}</span>{document.url && <ExternalLink size={12}/>}</a> : expectsDocument && <small className="document-missing-warning"><AlertTriangle size={12}/> El estado indica que existe un Excel. Reindexa la carpeta para recuperarlo.</small>}<div className="f29-document-actions"><button disabled={state?.status === 'loading' || !row.driveFolderId} onClick={onReload}><RefreshCw size={12}/> {document ? 'Reindexar' : 'Recargar mes'}</button><label><Upload size={12}/> {document ? 'Subir corrección' : 'Subir Excel'}<input type="file" accept=".xls,.xlsx,.xlsm,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event => { onUpload(event.target.files?.[0]); event.currentTarget.value = ''; }}/></label></div>{state && <small className={state.status}>{state.message}{state.authorize && <button onClick={() => void connectGoogleDrive()}> Autorizar</button>}</small>}</div>;
}

function F29DocumentReviewCell({ row, document, state, onReload, onUpload, onNotifyAdmin }: { row: ClientRow; document: ClientRow['f29Document']; state?: { status: 'loading' | 'success' | 'error'; message: string; authorize?: boolean }; onReload: () => void; onUpload: (file?: File) => void; onNotifyAdmin: () => void }) {
  const expectsDocument = ['A', 'C', 'D'].includes(row.statusCode ?? '');
  const reviewAlreadyRequested = row.reviewStatus === 'pending_admin_review' || row.reviewStatus === 'approved';
  return <div className="f29-document-cell">{document ? <a href={document.url ?? '#'} target={document.url ? '_blank' : undefined} rel="noreferrer" title={document.name}><FileSpreadsheet size={14}/><span>{document.name}</span>{document.url && <ExternalLink size={12}/>}</a> : expectsDocument && <small className="document-missing-warning"><AlertTriangle size={12}/> El estado indica que existe un Excel. Reindexa la carpeta para recuperarlo.</small>}<div className="f29-document-actions"><button disabled={state?.status === 'loading' || !row.driveFolderId} onClick={onReload}><RefreshCw size={12}/> {document ? 'Reindexar' : 'Recargar mes'}</button><label><Upload size={12}/> {document ? 'Subir correcciÃ³n' : 'Subir Excel'}<input type="file" accept=".xls,.xlsx,.xlsm,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event => { onUpload(event.target.files?.[0]); event.currentTarget.value = ''; }}/></label><button className="notify-admin-button" disabled={state?.status === 'loading' || !row.periodId || !document || reviewAlreadyRequested} onClick={onNotifyAdmin}><Send size={12}/> {row.reviewStatus === 'approved' ? 'RevisiÃ³n aprobada' : reviewAlreadyRequested ? 'Aviso enviado' : 'Avisar admin'}</button></div>{document && !reviewAlreadyRequested && <small className="document-review-hint">Confirma que el Excel estÃ¡ cargado e indexado antes de avisar a Richard.</small>}{state && <small className={state.status}>{state.message}{state.authorize && <button onClick={() => void connectGoogleDrive()}> Autorizar</button>}</small>}</div>;
}

function F29DocumentReviewCellV2({ row, document, state, onReload, onUpload, onNotifyAdmin }: { row: ClientRow; document: ClientRow['f29Document']; state?: { status: 'loading' | 'success' | 'error'; message: string; authorize?: boolean }; onReload: () => void; onUpload: (file?: File) => void; onNotifyAdmin: () => void }) {
  const expectsDocument = ['A', 'C', 'D'].includes(row.statusCode ?? '');
  const reviewAlreadyRequested = row.reviewStatus === 'pending_admin_review' || row.reviewStatus === 'approved';
  const notifyLabel = row.reviewStatus === 'approved' ? 'Revisión aprobada' : reviewAlreadyRequested ? 'Aviso enviado' : 'Avisar admin';
  return <div className="f29-document-cell">
    {document ? <a href={document.url ?? '#'} target={document.url ? '_blank' : undefined} rel="noreferrer" title={document.name}><FileSpreadsheet size={14}/><span>{document.name}</span>{document.url && <ExternalLink size={12}/>}</a> : expectsDocument && <small className="document-missing-warning"><AlertTriangle size={12}/> El estado indica que existe un Excel. Reindexa la carpeta para recuperarlo.</small>}
    <div className="f29-document-actions">
      <button disabled={state?.status === 'loading' || !row.driveFolderId} onClick={onReload}><RefreshCw size={12}/> {document ? 'Reindexar' : 'Recargar mes'}</button>
      <label><Upload size={12}/> {document ? 'Subir corrección' : 'Subir Excel'}<input type="file" accept=".xls,.xlsx,.xlsm,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event => { onUpload(event.target.files?.[0]); event.currentTarget.value = ''; }}/></label>
      <button className="notify-admin-button" disabled={state?.status === 'loading' || !row.periodId || !document || reviewAlreadyRequested} onClick={onNotifyAdmin}><Send size={12}/> {notifyLabel}</button>
    </div>
    {document && !reviewAlreadyRequested && <small className="document-review-hint">Confirma que el Excel está cargado e indexado antes de avisar a Richard.</small>}
    {state && <small className={state.status}>{state.message}{state.authorize && <button onClick={() => void connectGoogleDrive()}> Autorizar</button>}</small>}
  </div>;
}

function WorkflowProgress({ row }: { row: ClientRow }) {
  const steps = [
    ['Archivo cargado', Boolean(row.f29Document) || ['A','C','D','E'].includes(row.statusCode ?? '')],
    ['Revisión admin', row.reviewStatus === 'approved' || row.emailStatus === 'sent'],
    ['Informada al cliente', row.emailStatus === 'sent'],
    ['Pago confirmado', row.taxPaid],
  ] as const;
  return <ol className="f29-step-progress">{steps.map(([label, done]) => <li className={done ? 'done' : ''} key={label}><i>{done ? <Check size={11}/> : null}</i><span>{label}</span></li>)}</ol>;
}

function F29WorkflowProgress({ row }: { row: ClientRow }) {
  const steps = [
    ['Archivo cargado', Boolean(row.f29Document) || ['A','C','D','E'].includes(row.statusCode ?? '')],
    ['Aviso a admin', row.reviewStatus === 'pending_admin_review' || row.reviewStatus === 'approved' || row.emailStatus === 'sent'],
    ['Informada al cliente', row.emailStatus === 'sent'],
    ['Pago confirmado', row.taxPaid],
  ] as const;
  return <ol className="f29-step-progress">{steps.map(([label, done]) => <li className={done ? 'done' : ''} key={label}><i>{done ? <Check size={11}/> : null}</i><span>{label}</span></li>)}</ol>;
}

export function F29OperationsDashboard({ rows, updateRow, openClient, year, month, navigatePeriod, saveStates, reload, isAdmin }: { rows: ClientRow[]; updateRow: (id: string, patch: Partial<ClientRow>) => Promise<void>; openClient: (row: ClientRow) => void; year: number; month: number; navigatePeriod: (year: number, month: number) => void; saveStates: Record<string, 'saving' | 'saved' | 'error'>; reload: () => Promise<void>; isAdmin: boolean }) {
  const [query, setQuery] = useState(''); const [statusFilters, setStatusFilters] = useState<F29WorkflowFilter[]>(['pending']); const [responsibleFilters, setResponsibleFilters] = useState<string[]>([]); const [operationFilters, setOperationFilters] = useState<string[]>([]); const [onlyAlerts, setOnlyAlerts] = useState(false); const [filtersOpen, setFiltersOpen] = useState(false); const [page, setPage] = useState(1); const [emailRow, setEmailRow] = useState<ClientRow | null>(null); const [reminderRow, setReminderRow] = useState<ClientRow | null>(null); const [sort, setSort] = useState<SortState<F29SortKey>>({ key: 'client', direction: 'asc' });
  const [documentOverrides, setDocumentOverrides] = useState<Record<string, ClientRow['f29Document']>>({});
  const [documentState, setDocumentState] = useState<Record<string, { status: 'loading' | 'success' | 'error'; message: string; authorize?: boolean }>>({});
  const [inspectorId, setInspectorId] = useState<string | null>(null);
  const [inspectorTab, setInspectorTab] = useState<'summary' | 'documents' | 'history' | 'activity'>('summary');
  const documentFor = (row: ClientRow) => Object.prototype.hasOwnProperty.call(documentOverrides, row.id) ? documentOverrides[row.id] : row.f29Document;
  const reloadDocument = async (row: ClientRow) => { setDocumentState(current => ({ ...current, [row.id]: { status: 'loading', message: 'Revisando carpeta…' } })); try { await scanClientDrive(row.id, { year, month }); const document = await loadF29PeriodDocument(row.id, year, month); setDocumentOverrides(current => ({ ...current, [row.id]: document })); setDocumentState(current => ({ ...current, [row.id]: { status: 'success', message: document ? 'Excel encontrado e indexado.' : 'Carpeta revisada; no hay un Excel válido.' } })); await reload(); } catch (error) { setDocumentState(current => ({ ...current, [row.id]: { status: 'error', message: error instanceof Error ? error.message : 'No fue posible revisar la carpeta.', authorize: error instanceof DriveAuthorizationError } })); } };
  const uploadDocument = async (row: ClientRow, file?: File) => { if (!file) return; setDocumentState(current => ({ ...current, [row.id]: { status: 'loading', message: 'Subiendo Excel…' } })); try { const result = await uploadF29Excel(row.id, year, month, file); setDocumentOverrides(current => ({ ...current, [row.id]: result.document })); setDocumentState(current => ({ ...current, [row.id]: { status: 'success', message: 'Excel subido, indexado y disponible para el correo.' } })); await reload(); } catch (error) { setDocumentState(current => ({ ...current, [row.id]: { status: 'error', message: error instanceof Error ? error.message : 'No fue posible subir el Excel.', authorize: error instanceof DriveAuthorizationError } })); } };
  const notifyAdminReview = async (row: ClientRow) => { const document = documentFor(row); if (!row.periodId || !document) return; const ok = window.confirm(`Confirma que el Excel de ${row.name} está correctamente cargado e indexado. Se enviará aviso a richard@ainahue.cl y quedará registro del aviso.`); if (!ok) return; setDocumentState(current => ({ ...current, [row.id]: { status: 'loading', message: 'Enviando aviso a administración...' } })); try { await sendF29AdminReview(row.periodId, document.id); setDocumentState(current => ({ ...current, [row.id]: { status: 'success', message: 'Aviso enviado a richard@ainahue.cl y registrado.' } })); await reload(); } catch (error) { setDocumentState(current => ({ ...current, [row.id]: { status: 'error', message: error instanceof Error ? error.message : 'No fue posible avisar a administración.' } })); } };
  const markPaid = async (row: ClientRow) => { if (!row.periodId) return; await markF29Payment(row.periodId, true); await reload(); };
  const pageSize = 100;
  const responsibles = [...new Set(rows.map(row => row.accountant).filter(Boolean))].sort();
  useEffect(() => setStatusFilters(['pending']), [year, month]);
  useEffect(() => setPage(1), [query, statusFilters, responsibleFilters, operationFilters, onlyAlerts, year, month]);
  const filtered = useMemo(() => rows.filter(row =>
    `${row.rut} ${row.name} ${row.accountingCode ?? ''}`.toLowerCase().includes(query.trim().toLowerCase()) &&
    (!statusFilters.length || statusFilters.some(filter => matchesF29Workflow(row, filter))) &&
    (!responsibleFilters.length || responsibleFilters.includes(row.accountant)) && (!onlyAlerts || isF29Alert(row)) &&
    (!operationFilters.length || operationFilters.some(filter => (filter === 'email' && row.emailStatus !== 'sent') || (filter === 'unpaid' && !row.taxPaid && (row.amount ?? 0) > 0) || (filter === 'paid' && row.taxPaid) || (filter === 'reminded' && Boolean(row.taxLastReminderAt))))
  ).sort((a, b) => {
    const values: Record<F29SortKey, (row: ClientRow) => string | number | boolean | null> = {
      client: row => row.rut, responsible: row => row.accountant, status: row => row.statusLabel,
      payment: row => row.taxPaid ? 2 : (row.amount ?? 0) > 0 ? 1 : 0, amount: row => row.amount,
      alerts: row => row.observation || (isF29Alert(row) ? row.statusLabel : ''),
    };
    return compareSortValues(values[sort.key](a), values[sort.key](b), sort.direction) || a.rut.localeCompare(b.rut, 'es', { numeric: true });
  }), [rows, query, statusFilters, responsibleFilters, onlyAlerts, operationFilters, sort]);
  const shown = filtered.slice((page - 1) * pageSize, page * pageSize); const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize));
  const periods = rows.filter(row => row.periodId); const pending = rows.filter(row => matchesF29Workflow(row, 'pending')).length; const loaded = periods.filter(row => row.statusCode === 'A').length; const informed = periods.filter(row => row.statusCode === 'C').length; const paid = periods.filter(row => row.taxPaid || row.statusCode === 'D').length; const missing = rows.filter(row => !row.periodId || row.statusCode === null).length;
  const inspectorRow = inspectorId ? rows.find(row => row.id === inspectorId) ?? null : null;
  const selectInspector = (row: ClientRow) => { setInspectorId(row.id); setInspectorTab('summary'); };
  return <div className={`f29-command-layout ${inspectorRow ? 'has-inspector' : ''}`}><div className="control-content wide-content"><div className="control-page-head"><div><span>Operación mensual</span><h1>F29 <i>/</i> Operaciones</h1><p>{MONTHS[month - 1]} {year} · control de declaraciones, comunicaciones y pago.</p></div><div className="page-actions period-controls"><select aria-label="Mes F29" value={month} onChange={event => navigatePeriod(year, Number(event.target.value))}>{MONTHS.map((name,index) => <option value={index + 1} key={name}>{name}</option>)}</select><select aria-label="Año F29" value={year} onChange={event => navigatePeriod(Number(event.target.value), month)}>{[2025,2026,2027].map(value => <option key={value}>{value}</option>)}</select></div></div>
    <div className="f29-ops-kpis workflow-kpis" data-help="f29-kpis"><div><span>Clientes</span><strong>{rows.length}</strong></div><div><span>Pendientes <ContextualTooltip label="Qué significa pendiente">Todo período clasificado que aún no está pagado. Excluye Sin movimiento y Sin estado.</ContextualTooltip></span><strong className={pending ? 'negative' : ''}>{pending}</strong></div><div><span>Cargadas</span><strong>{loaded}</strong></div><div><span>Informadas</span><strong>{informed}</strong></div><div><span>Pagadas</span><strong>{paid}</strong></div><div><span>Sin estado <ContextualTooltip label="Qué significa sin estado">El contador responsable debe clasificar estos períodos.</ContextualTooltip></span><strong className={missing ? 'negative' : ''}>{missing}</strong></div></div>
    {inspectorRow&&<section className="operations-card f29-selected-progress"><header><div><small>Flujo del cliente seleccionado</small><strong>{inspectorRow.name}</strong></div>{!inspectorRow.taxPaid&&inspectorRow.emailStatus==='sent'&&<button className="button-dark" disabled={!inspectorRow.periodId} onClick={()=>void markPaid(inspectorRow)}><Check size={14}/>Marcar como pagada</button>}</header><F29WorkflowProgress row={inspectorRow}/></section>}
    <section className="operations-card"><div className="table-toolbar f29-toolbar"><div className="toolbar-search"><Search size={16} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar RUT, razón social o Conta…" /></div><button className={`mobile-filter-toggle ${filtersOpen?'active':''}`} onClick={()=>setFiltersOpen(value=>!value)}><SlidersHorizontal size={14}/>Filtros{statusFilters.length + responsibleFilters.length + operationFilters.length + Number(onlyAlerts)>0&&<b>{statusFilters.length + responsibleFilters.length + operationFilters.length + Number(onlyAlerts)}</b>}</button><div className={`mobile-filter-strip ${filtersOpen?'is-open':''}`}><MultiSelectFilter label="Etapas" allLabel="Todas las etapas" options={workflowOptions} values={statusFilters} onChange={values=>setStatusFilters(values as F29WorkflowFilter[])}/><MultiSelectFilter label="Responsables" allLabel="Todos los responsables" options={responsibles.map(name=>({value:name,label:name}))} values={responsibleFilters} onChange={setResponsibleFilters}/><MultiSelectFilter label="Operación" allLabel="Email y pago: todos" options={operationOptions} values={operationFilters} onChange={setOperationFilters}/><button className={`filter-button ${onlyAlerts ? 'active' : ''}`} onClick={() => setOnlyAlerts(value => !value)}><AlertTriangle size={15} /> Alertas</button></div></div>
      <div className="table-scroll command-table-scroll"><table className="ops-table f29-command-table"><thead><tr><SortableHeader label="Cliente / RUT" sort={sort} sortKey="client" onSort={key=>setSort(current=>nextSort(current,key))}/><SortableHeader label="Responsable" sort={sort} sortKey="responsible" onSort={key=>setSort(current=>nextSort(current,key))}/><SortableHeader label="Estado F29" sort={sort} sortKey="status" onSort={key=>setSort(current=>nextSort(current,key))}/><SortableHeader label="Pago" sort={sort} sortKey="payment" onSort={key=>setSort(current=>nextSort(current,key))}/><SortableHeader label="Monto" sort={sort} sortKey="amount" onSort={key=>setSort(current=>nextSort(current,key))}/><SortableHeader label="Alertas" sort={sort} sortKey="alerts" onSort={key=>setSort(current=>nextSort(current,key))}/></tr></thead><tbody>{shown.map(row => <tr key={`command-${row.id}`} className={`${inspectorId===row.id?'is-selected ':''}${!row.periodId?'missing-period-row':''}`} onClick={()=>selectInspector(row)}><td><span className="command-client"><strong>{row.name}</strong><small>{row.rut}{row.accountingCode?` · Conta ${row.accountingCode}`:''}</small></span></td><td><span className="command-responsible"><span className={`avatar ${responsibleTone[row.accountant.toUpperCase()]??'responsible-default'}`}>{row.initials}</span>{row.accountant}</span></td><td><span className={`status-pill ${row.statusCode ? statusTone[row.statusCode] : 'is-neutral'}`}><i/>{row.statusLabel||'Sin estado'}</span></td><td><span className={`status-pill ${row.taxPaid?'is-paid':(row.amount??0)>0?'is-pending':'is-neutral'}`}><i/>{row.taxPaid?'Pagado':(row.amount??0)>0?'Pendiente':'Sin pago'}</span></td><td className="command-amount">{row.amount===null?'—':money.format(row.amount)}</td><td>{row.observation?<span className="command-alert" title={row.observation}><AlertTriangle size={13}/>{row.observation}</span>:isF29Alert(row)?<span className="command-alert"><AlertTriangle size={13}/>{row.statusLabel}</span>:<span className="command-empty">—</span>}</td></tr>)}</tbody></table></div>
      <div className="f29-mobile-list" aria-label="Clientes F29">{shown.map(row => <article className={`f29-mobile-card ${!row.periodId ? 'missing-period-row' : ''}`} key={`mobile-${row.id}`}><button className="mobile-record-open" onClick={()=>selectInspector(row)}><span className="mobile-record-head"><span><strong>{row.name}</strong><small>{row.rut} · {row.accountant}</small></span><span className={`status-pill ${row.statusCode ? statusTone[row.statusCode] : 'is-neutral'}`}><i/>{row.statusLabel||'Sin estado'}</span></span><span className="mobile-record-bottom"><strong>{row.amount===null?'—':money.format(row.amount)}</strong><span className={row.taxPaid?'paid':'pending'}><i/>{row.taxPaid?'Pagado':(row.amount??0)>0?'Pendiente':'Sin pago'}</span><span>{row.emailStatus==='sent'?'Email enviado':'Email pendiente'}</span></span>{row.observation&&<span className="mobile-record-alert"><AlertTriangle size={12}/>{row.observation}</span>}</button></article>)}</div>
      <footer className="table-footer"><span>Mostrando {shown.length} de {filtered.length} clientes</span><span className="pagination"><button disabled={page === 1} onClick={() => setPage(value => value - 1)}>Anterior</button><b>{page} / {pageCount}</b><button disabled={page === pageCount} onClick={() => setPage(value => value + 1)}>Siguiente</button></span></footer></section>
    {emailRow && <F29MailComposer row={emailRow} onClose={() => setEmailRow(null)} onSent={reload} />}{reminderRow && <F29MailComposer row={reminderRow} mode="tax-reminder" onClose={() => setReminderRow(null)} onSent={reload} />}
  </div>{inspectorRow&&<aside className="operation-inspector" aria-label={`Inspector de ${inspectorRow.name}`}><header><div><span>Cliente F29</span><h2>{inspectorRow.name}</h2><small>{inspectorRow.rut}{inspectorRow.accountingCode?` · Conta ${inspectorRow.accountingCode}`:''}</small></div><button aria-label="Cerrar inspector" onClick={()=>setInspectorId(null)}><X size={18}/></button></header><nav className="inspector-tabs" aria-label="Secciones del inspector"><button className={inspectorTab==='summary'?'active':''} onClick={()=>setInspectorTab('summary')}>Resumen</button><button className={inspectorTab==='documents'?'active':''} onClick={()=>setInspectorTab('documents')}>Documentos</button><button className={inspectorTab==='history'?'active':''} onClick={()=>setInspectorTab('history')}>Historial</button><button className={inspectorTab==='activity'?'active':''} onClick={()=>setInspectorTab('activity')}>Actividad</button></nav><div className="inspector-scroll">
    {inspectorTab==='summary'&&<><section className="inspector-status"><span className={`status-pill ${inspectorRow.statusCode?statusTone[inspectorRow.statusCode]:'is-neutral'}`}><i/>{inspectorRow.statusLabel||'Sin estado'}</span><SaveState state={saveStates[inspectorRow.id]}/></section><section className="inspector-fields"><label>Responsable<select className={`inline-select responsible-select ${responsibleTone[inspectorRow.accountant.toUpperCase()]??'responsible-default'}`} value={inspectorRow.accountant} onChange={event=>void updateRow(inspectorRow.id,{accountant:event.target.value})}>{responsibles.map(name=><option key={name}>{name}</option>)}</select></label><label>Monto F29<CommitInput className="inline-number" label={`Monto F29 de ${inspectorRow.name}`} value={inspectorRow.amount} onCommit={value=>void updateRow(inspectorRow.id,{amount:value?Number(value):null})}/></label><label>Estado F29<select className={`inline-status ${inspectorRow.statusCode?statusTone[inspectorRow.statusCode]:'is-neutral'}`} value={inspectorRow.statusCode??''} onChange={event=>{const code=event.target.value as F29StatusCode;void updateRow(inspectorRow.id,{statusCode:code,statusLabel:F29_STATUS_LABELS[code]})}}><option value="">Sin estado</option>{Object.entries(F29_STATUS_LABELS).map(([code,label])=><option value={code} key={code}>{label}</option>)}</select></label><label>Fecha<input className="inline-date" type="date" value={inspectorRow.filedDate??''} onChange={event=>void updateRow(inspectorRow.id,{filedDate:event.target.value||null})}/></label></section>{inspectorRow.observation&&<section className="inspector-alert"><AlertTriangle size={15}/><span><strong>Alerta operativa</strong>{inspectorRow.observation}</span></section>}<section className="inspector-section"><h3>Acciones rápidas</h3><div className="inspector-actions"><button disabled={!inspectorRow.periodId} onClick={()=>setEmailRow(inspectorRow)}><Mail size={15}/>Enviar F29</button><button disabled={(inspectorRow.amount??0)<=0||inspectorRow.taxPaid} onClick={()=>setReminderRow(inspectorRow)}><Send size={15}/>Recordar pago</button><button onClick={()=>openClient(inspectorRow)}><MoreHorizontal size={15}/>Ficha completa</button></div></section><section className="inspector-section"><h3>Contacto</h3><dl><div><dt>Email</dt><dd>{inspectorRow.legalRepresentativeEmail||'No informado'}</dd></div><div><dt>Teléfono</dt><dd>{inspectorRow.phone||'No informado'}</dd></div></dl></section><section className="inspector-section"><h3>Nota interna</h3>{isAdmin?<CommitInput className="inline-note inspector-note" label={`Observación de ${inspectorRow.name}`} value={inspectorRow.observation} onCommit={value=>void updateRow(inspectorRow.id,{observation:value})}/>:<p>{inspectorRow.observation||'Sin observaciones.'}</p>}</section></>}
    {inspectorTab==='documents'&&<section className="inspector-section inspector-tab-panel"><FolderOpen size={20}/><h3>Documento del período</h3><F29DocumentReviewCellV2 row={inspectorRow} document={documentFor(inspectorRow)} state={documentState[inspectorRow.id]} onReload={()=>void reloadDocument(inspectorRow)} onUpload={file=>void uploadDocument(inspectorRow,file)} onNotifyAdmin={()=>void notifyAdminReview(inspectorRow)}/></section>}
    {inspectorTab==='history'&&<section className="inspector-section inspector-tab-panel"><History size={20}/><h3>Contexto del período</h3><dl><div><dt>Monto anterior</dt><dd>{inspectorRow.previousAmount===null?'—':money.format(inspectorRow.previousAmount)}</dd></div><div><dt>Último recordatorio</dt><dd>{inspectorRow.taxLastReminderAt?new Intl.DateTimeFormat('es-CL',{dateStyle:'medium'}).format(new Date(inspectorRow.taxLastReminderAt)):'Sin envíos'}</dd></div><div><dt>Actualización</dt><dd>{inspectorRow.updated}</dd></div></dl></section>}
    {inspectorTab==='activity'&&<section className="inspector-section inspector-tab-panel"><Activity size={20}/><h3>Actividad reciente</h3><p>Los cambios de estado, correos y pagos quedan registrados en la trazabilidad del cliente.</p><button className="button-ghost" onClick={()=>openClient(inspectorRow)}>Abrir actividad completa</button></section>}
  </div></aside>}</div>;
}
