import { useEffect, useMemo, useState, type ClipboardEvent } from 'react';
import { AlertTriangle, Check, Clock3, ExternalLink, FileSpreadsheet, Image, Paperclip, Send, Trash2, Upload, X } from 'lucide-react';
import { renderNetzEmail } from '../shared/email-template';
import { loadClientDocuments } from './client-api';
import { driveAttachment, loadClientContacts, loadEmailTemplate, loadLastEmailRecipients, loadStoredAttachments, resolveEmployeeDirectoryEmail, sendF29Email, sendF29PaymentReminder, uploadEmailAttachment } from './communication-api';
import type { ClientDocument, ClientRow, EmailAttachment } from './types';
import { compareF29Documents, isF29Workbook } from './document-matching';

const months = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const money = new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 });
const displayDate = (value: string | null) => value ? new Intl.DateTimeFormat('es-CL', { dateStyle: 'long' }).format(new Date(`${value.slice(0, 10)}T12:00:00`)) : 'Pendiente';
const interpolate = (value: string, vars: Record<string,string>) => value.replace(/{{\s*([a-z0-9_]+)\s*}}/gi, (_, key) => vars[key] ?? '—');
const safeHtml = (value: string) => value.replace(/<\s*(script|style|iframe)[^>]*>[\s\S]*?<\s*\/\s*\1\s*>/gi, '').replace(/\son\w+\s*=\s*("[^"]*"|'[^']*')/gi, '');
const addresses = (value: string) => [...new Set(value.split(/[;,]/).map(item => item.trim().toLowerCase()).filter(Boolean))];
const formatSize = (size?: number) => size ? size < 1024 * 1024 ? `${Math.max(1, Math.round(size / 1024))} KB` : `${(size / 1024 / 1024).toFixed(1)} MB` : 'Tamaño disponible al cargar';
const typeLabel = (item: EmailAttachment) => item.mimeType?.startsWith('image/') ? 'Imagen · comprobante visual' : item.mimeType === 'application/vnd.google-apps.spreadsheet' ? 'Google Sheets · se exportará a Excel' : item.mimeType?.includes('pdf') ? 'Documento PDF' : item.mimeType?.includes('sheet') || /\.xlsx?$/i.test(item.fileName) ? 'Planilla Excel' : item.mimeType || 'Documento adjunto';
const sourceLabel = (item: EmailAttachment) => item.mimeType?.startsWith('image/') ? 'Comprobante visual · se muestra en el correo y se adjunta' : item.source === 'drive' ? (item.mimeType === 'application/vnd.google-apps.spreadsheet' ? 'Exportado desde Google Drive · Excel' : 'Archivo de Google Drive') : 'Archivo privado adjunto';
const sameAttachment = (left: EmailAttachment, right: EmailAttachment) => Boolean((left.id && left.id === right.id) || (left.documentId && left.documentId === right.documentId));

function suggestedDocument(document: ClientDocument, row: ClientRow) {
  return isF29Workbook({ name: document.name, path: document.drivePath, mimeType: document.mimeType, isFolder: document.isFolder }, row.year, row.month);
}

function AttachmentReview({ items, busy, onRemove, onReplace }: { items: EmailAttachment[]; busy: boolean; onRemove: (item: EmailAttachment) => void; onReplace: (item: EmailAttachment, file?: File) => void }) {
  const proofs = items.filter(item => item.mimeType?.startsWith('image/'));
  const attachments = items.filter(item => !item.mimeType?.startsWith('image/'));
  const renderItem = (item: EmailAttachment) => <article className={item.mimeType?.startsWith('image/') ? 'is-proof' : ''} key={item.id ?? item.documentId ?? item.fileName}>{item.previewUrl && <img src={item.previewUrl} alt={`Vista previa de ${item.fileName}`} />}<div className="attachment-metadata"><strong title={item.fileName}>{item.fileName}</strong><span className="attachment-kind">{item.mimeType?.startsWith('image/') ? 'COMPROBANTE INLINE + ADJUNTO' : 'ARCHIVO ADJUNTO'}</span><span>{typeLabel(item)}</span><span>{formatSize(item.sizeBytes)} · {sourceLabel(item)}</span></div><div className="attachment-item-actions">{item.source === 'storage' && <label className="replace-attachment"><Upload size={14}/><span>Reemplazar</span><input type="file" accept=".pdf,.xls,.xlsx,.xlsm,image/png,image/jpeg" disabled={busy} onChange={event => onReplace(item, event.target.files?.[0])}/></label>}<button type="button" disabled={busy} onClick={() => onRemove(item)}><Trash2 size={14}/> Quitar</button></div></article>;
  return <section className="attachment-review" aria-label="Archivos que se enviarán"><div className="attachment-review-head"><div><strong>Archivos incluidos en el envío</strong><small>{items.length ? `${attachments.length} adjunto(s) · ${proofs.length} comprobante(s) inline` : 'Sin archivos. Puedes continuar y enviar solo el mensaje.'}</small></div></div>{!items.length && <div className="attachment-empty"><Paperclip size={17}/><span>No hay archivos seleccionados.</span></div>}{proofs.length > 0 && <div className="attachment-group"><div className="attachment-group-title"><Image size={14}/><span>Comprobantes visibles en el correo</span></div>{proofs.map(renderItem)}</div>}{attachments.length > 0 && <div className="attachment-group"><div className="attachment-group-title"><Paperclip size={14}/><span>Adjuntos descargables</span></div>{attachments.map(renderItem)}</div>}</section>;
}

export function F29MailComposer({ row, mode = 'summary', onClose, onSent }: { row: ClientRow; mode?: 'summary' | 'tax-reminder'; onClose: () => void; onSent: () => Promise<void> }) {
  const previewMode = import.meta.env.DEV && new URLSearchParams(window.location.search).has('preview');
  const [to, setTo] = useState(''); const [extraCc, setExtraCc] = useState(''); const [responsibleEmail, setResponsibleEmail] = useState(row.accountantEmail); const [subject, setSubject] = useState(''); const [body, setBody] = useState(''); const [lastRecipients, setLastRecipients] = useState<string[]>([]);
  const [documents, setDocuments] = useState<ClientDocument[]>([]); const [stored, setStored] = useState<EmailAttachment[]>([]); const [selected, setSelected] = useState<EmailAttachment[]>([]);
  const [stage, setStage] = useState<'edit'|'preview'|'confirm'>('edit'); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [sending, setSending] = useState(false); const [error, setError] = useState(''); const [attachmentFault, setAttachmentFault] = useState('');
  const isReminder = mode === 'tax-reminder';
  const requiredCc = [...new Set([responsibleEmail.trim().toLowerCase(), 'richard@ainahue.cl'].filter(Boolean))];
  const toList = addresses(to); const extraCcList = addresses(extraCc); const allCc = [...new Set([...requiredCc, ...extraCcList])];
  const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/; const invalidAddress = [...toList, ...extraCcList].find(email => !emailPattern.test(email));
  const variables = useMemo<Record<string,string>>(() => ({ client_name: row.name, month_name: months[row.month - 1], year: String(row.year), amount: money.format(row.amount ?? 0), filed_date: displayDate(row.filedDate || new Date().toISOString().slice(0,10)), payment_due_date: displayDate(row.taxPaymentDueDate), payment_status: row.statusLabel, due_day: row.dueDay ? String(row.dueDay) : '—', firm_name: 'Netz Asesorías' }), [row]);

  useEffect(() => { void (async () => { try {
    const [contacts, template, last, docs, uploads, resolvedResponsible] = await Promise.all([loadClientContacts(row.id), loadEmailTemplate(isReminder ? 'f29_payment_reminder' : 'f29_monthly_summary'), loadLastEmailRecipients(row.id, isReminder ? 'f29_payment_reminder' : 'f29_summary'), previewMode ? Promise.resolve([]) : loadClientDocuments(row.id), row.periodId ? loadStoredAttachments(row.periodId) : Promise.resolve([]), row.accountantEmail ? Promise.resolve(row.accountantEmail) : resolveEmployeeDirectoryEmail(row.accountant)]);
    const contactEmails = contacts.filter(item => item.isActive && item.isBilling).map(item => item.email);
    setLastRecipients(last); setTo((contactEmails.length ? contactEmails : last).join(', ')); setResponsibleEmail(resolvedResponsible); setSubject(template.subject); setBody(template.bodyHtml); setDocuments(docs.filter(item => !item.isFolder)); setStored(uploads);
  } catch (reason) { setError(reason instanceof Error ? reason.message : 'No fue posible preparar el correo.'); } finally { setLoading(false); } })(); }, [row.id, row.periodId, row.accountant, row.accountantEmail, isReminder, previewMode]);

  const periodDocuments = documents.filter(document => suggestedDocument(document, row)).sort((left, right) => compareF29Documents(
    { name: left.name, path: left.drivePath, mimeType: left.mimeType, modifiedAt: left.modifiedAt },
    { name: right.name, path: right.drivePath, mimeType: right.mimeType, modifiedAt: right.modifiedAt },
    row.year,
    row.month,
  ));
  const exactFolder = periodDocuments;
  const suggestedIds = new Set(periodDocuments.filter(document => suggestedDocument(document,row)).map(document => document.id));
  const toggle = (attachment: EmailAttachment) => setSelected(current => current.some(item => sameAttachment(item, attachment)) ? current.filter(item => !sameAttachment(item, attachment)) : [...current, attachment]);
  const remove = (attachment: EmailAttachment) => setSelected(current => current.filter(item => !sameAttachment(item, attachment)));
  const upload = async (file?: File, replacing?: EmailAttachment) => { if (!file || !row.periodId) return; setUploading(true); setError(''); try { const result = await uploadEmailAttachment(row.id,row.periodId,file); setStored(current => [result,...current]); setSelected(current => replacing ? [...current.filter(item => !sameAttachment(item, replacing)), result] : [...current,result]); setAttachmentFault(''); } catch (reason) { const message = reason instanceof Error ? reason.message : 'No fue posible subir el archivo.'; setError(message); setAttachmentFault(`El archivo no quedó listo: ${message}`); } finally { setUploading(false); } };
  const pasteImage = (event: ClipboardEvent<HTMLDivElement>) => { const image = [...event.clipboardData.files].find(file => file.type.startsWith('image/')); if (!image) return; event.preventDefault(); const extension = image.type === 'image/jpeg' ? 'jpg' : 'png'; void upload(new File([image], `comprobante-sii-${row.year}-${String(row.month).padStart(2,'0')}-${Date.now()}.${extension}`, { type: image.type })); };
  const submit = async (schedule = false) => { if (!row.periodId || uploading || attachmentFault) return; if (!responsibleEmail) return setError('El responsable debe tener un email configurado.'); if (invalidAddress || !toList.length) return setError('Revisa los destinatarios ingresados.'); setSending(true); setError(''); try { if (isReminder) await sendF29PaymentReminder(row.periodId,toList,allCc,subject,body); else await sendF29Email(row.periodId,toList,allCc,subject,body,selected,schedule); await onSent(); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No fue posible enviar el correo.'); } finally { setSending(false); } };
  const previewSubject = interpolate(subject,variables); const previewBody = `${safeHtml(interpolate(body,variables))}${!isReminder ? `<p style="margin-top:18px;color:#6b7782;font-size:12px"><strong>Primer envío registrado:</strong> ${row.emailSentAt ? displayDate(row.emailSentAt) : 'Aún no enviado'}</p>` : ''}`;
  const previewEmail = renderNetzEmail({ title: isReminder ? 'Recordatorio de pago F29' : 'Formulario 29 del período', eyebrow: isReminder ? 'Comunicación de cobranza' : 'Información tributaria', clientName: row.name, periodOrConcept: `${months[row.month - 1]} ${row.year}`, bodyHtml: previewBody, summary: isReminder ? [{ label: 'Cliente', value: row.name }, { label: 'Período', value: `${months[row.month - 1]} ${row.year}` }, { label: 'Monto pendiente', value: money.format(row.amount ?? 0) }, { label: 'Vencimiento', value: row.dueDay ? `Día ${row.dueDay}` : 'Por confirmar' }] : [{ label: 'Período', value: `${months[row.month - 1]} ${row.year}` }, { label: 'Monto informado', value: money.format(row.amount ?? 0) }, { label: 'Estado', value: row.statusLabel }, { label: 'Fecha de presentación', value: displayDate(row.filedDate) }, { label: 'Fecha de pago', value: displayDate(row.taxPaymentDueDate) }], attachments: selected.map(item => ({ name: item.fileName, detail: sourceLabel(item) })), proofs: selected.flatMap(item => item.mimeType?.startsWith('image/') && item.previewUrl ? [{ name: item.fileName, src: item.previewUrl }] : []), responsibleName: row.accountant, replyTo: responsibleEmail || undefined, logoUrl: import.meta.env.VITE_BRAND_LOGO_URL });
  const actionsDisabled = loading || uploading || sending;
  const canPreview = Boolean(toList.length && !invalidAddress && subject.trim() && body.trim() && responsibleEmail && !attachmentFault && !uploading);

  return <div className="modal-backdrop"><section className="control-modal f29-mail-composer" aria-busy={actionsDisabled} aria-label="Compositor de correo F29"><header><div><span>{isReminder ? 'Pago mensual F29' : 'Comunicación F29'}</span><h2>{isReminder ? 'Recordatorio pago F29' : 'Preparar email F29'}</h2><small>{row.name} · {months[row.month - 1]} {row.year}</small></div><button disabled={actionsDisabled} aria-label="Cerrar compositor" onClick={onClose}><X size={18}/></button></header><div className="composer-scroll">{loading ? <div className="composer-loading"><span className="loading-spinner"/><strong>Preparando correo</strong><small>Cargando destinatarios, plantilla y archivos del período…</small></div> : <><div className="composer-steps"><b className={stage==='edit'?'active':''}>1. Preparar</b><b className={stage==='preview'?'active':''}>2. Revisar</b><b className={stage==='confirm'?'active':''}>3. Confirmar</b></div>
    {stage==='edit' ? <div className="f29-mail-grid"><label>Para · uno o varios destinatarios<input disabled={actionsDisabled} value={to} onChange={event=>setTo(event.target.value)} placeholder="cliente@empresa.cl, administracion@empresa.cl" /></label><small className="recipient-help">Separa varios correos con coma o punto y coma.</small>{lastRecipients.length>0 && <div className="recipient-suggestions"><small>Últimos destinatarios utilizados</small>{lastRecipients.map(email=><button type="button" key={email} onClick={()=>setTo(current=>[...new Set([...addresses(current),email])].join(', '))}>+ {email}</button>)}</div>}<label>CC obligatorio<input value={requiredCc.join(', ')} readOnly /></label>{!responsibleEmail && <p className="form-error">El responsable {row.accountant} no tiene email activo en Configuración → Equipo y acceso.</p>}<label>CC adicionales<input disabled={actionsDisabled} value={extraCc} onChange={event=>setExtraCc(event.target.value)} placeholder="supervisor@empresa.cl; otro@empresa.cl" /></label><small className="recipient-help">Estos correos se agregarán a los CC obligatorios.</small>{invalidAddress && <p className="form-error">La dirección “{invalidAddress}” no es válida.</p>}<label>Asunto<input disabled={actionsDisabled} value={subject} onChange={event=>setSubject(event.target.value)} /></label><label>Mensaje del correo<textarea disabled={actionsDisabled} value={body} onChange={event=>setBody(event.target.value)} /></label>
      {!isReminder && <section className="period-files"><div><strong><Paperclip size={14}/> Archivos disponibles · /f29/{row.year}/{String(row.month).padStart(2,'0')}</strong><small>{exactFolder.length ? `${exactFolder.length} archivo(s) encontrados en la carpeta del período.` : 'No se encontró la ruta exacta; se muestran los archivos F29 disponibles para control.'}</small></div><div className="period-file-list">{stored.map(item=><button type="button" disabled={actionsDisabled} key={item.id} className={selected.some(value=>sameAttachment(value,item))?'selected':''} onClick={()=>toggle(item)}><Image size={14}/><span>{item.fileName}<small>{typeLabel(item)} · {sourceLabel(item)}</small></span>{selected.some(value=>sameAttachment(value,item))&&<Check size={13}/>}</button>)}{periodDocuments.map(document=>{const attachment=driveAttachment(document);const active=selected.some(value=>value.documentId===document.id);const suggested=suggestedIds.has(document.id);return <button type="button" disabled={actionsDisabled} key={document.id} className={`${active?'selected ':''}${suggested?'suggested':''}`} onClick={()=>toggle(attachment)}><FileSpreadsheet size={14}/><span>{document.name}<small>{suggested?'Sugerido · ':''}{document.mimeType === 'application/vnd.google-apps.spreadsheet' ? 'Exportado a Excel · ' : 'Drive · '}{document.drivePath}</small></span>{active?<Check size={13}/>:<ExternalLink size={12}/>}</button>})}</div>{!periodDocuments.length&&<p className="empty-folder"><Paperclip size={16}/> No hay archivos indexados para este período. Puedes subir uno o enviar sin adjuntos.</p>}<div className="attachment-actions"><label className="upload-button"><Upload size={14}/><input type="file" accept=".pdf,.xls,.xlsx,.xlsm,image/png,image/jpeg" disabled={actionsDisabled} onChange={event=>void upload(event.target.files?.[0])}/>{uploading?'Subiendo y verificando…':'Subir archivo'}</label><div className="paste-screenshot" tabIndex={0} onPaste={pasteImage}><Image size={15}/> Pegar captura de SII con Ctrl+V <small>Se verá inline y también irá adjunta</small></div></div></section>}
      {!isReminder && <AttachmentReview items={selected} busy={actionsDisabled} onRemove={remove} onReplace={(item,file)=>void upload(file,item)}/>}</div> : <div className="email-preview"><strong>{previewSubject}</strong><p><b>Para:</b> {toList.join(', ')||'—'}</p><p><b>CC:</b> {allCc.join(', ')}</p>{row.statusCode!=='A'&&!isReminder&&<div className="status-review-warning"><AlertTriangle size={16}/><span><b>Estado actual: {row.statusLabel}</b> — revise antes de enviar; se esperaba Cargada.</span></div>}<article className="rendered-email" dangerouslySetInnerHTML={{__html:previewEmail}}/>{!isReminder&&<AttachmentReview items={selected} busy={actionsDisabled} onRemove={remove} onReplace={(item,file)=>void upload(file,item)}/>} {stage==='confirm'&&<div className="confirm-warning"><AlertTriangle size={16}/>Confirma destinatarios, contenido y archivos. El envío quedará registrado.</div>}</div>}
    {(attachmentFault || error)&&<p className="form-error composer-error" role="alert"><AlertTriangle size={16}/><span>{attachmentFault || error}</span></p>}</>}</div><footer className="composer-sticky-actions"><span className="composer-action-summary">{selected.length} archivo(s) · paso {stage==='edit'?'1 de 3':stage==='preview'?'2 de 3':'3 de 3'}</span><button className="button-ghost" disabled={actionsDisabled} onClick={stage==='edit'?onClose:()=>setStage('edit')}>{stage==='edit'?'Cancelar':'Volver a editar'}</button>{stage==='edit'&&<button className="button-dark" disabled={!canPreview||actionsDisabled} onClick={()=>setStage('preview')}>Vista previa</button>}{stage==='preview'&&<button className="button-dark" disabled={actionsDisabled||Boolean(attachmentFault)} onClick={()=>setStage('confirm')}>Confirmar envío</button>}{stage==='confirm'&&<><button className="button-dark" disabled={actionsDisabled||Boolean(attachmentFault)} onClick={()=>void submit(false)}><Send size={14}/>{sending?'Enviando y registrando…':'Enviar ahora'}</button>{!isReminder&&<button className="button-schedule" disabled={actionsDisabled||Boolean(attachmentFault)} onClick={()=>void submit(true)}><Clock3 size={14}/>{sending?'Programando…':'Programar envío'}</button>}</>}</footer></section></div>;
}
