import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, ExternalLink, FileSpreadsheet, FolderOpen, Search } from 'lucide-react';
import { supabase } from './supabase';
import { classifyDocument } from './client-api';
import type { DocumentKind } from './types';

type DocumentRow = { id: string; fileName: string; url: string | null; clientName: string; rut: string; type: DocumentKind; inferredType: DocumentKind | null; source: 'inferred' | 'manual'; path: string; modifiedAt: string | null };
type ActivityRow = { id: number; action: string; clientName: string; actor: string; createdAt: string; entityType: string };

export function DocumentsWorkspace() {
  const [documents,setDocuments]=useState<DocumentRow[]>([]); const [query,setQuery]=useState(''); const [type,setType]=useState('all'); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const load=async()=>{if(!supabase){setLoading(false);return;}const {data,error:queryError}=await supabase.from('documents').select('id,file_name,drive_web_view_link,document_type,inferred_document_type,classification_source,modified_at,drive_metadata,clients(legal_name,rut)').neq('mime_type','application/vnd.google-apps.folder').order('modified_at',{ascending:false}).limit(500);if(queryError){setError(queryError.message);setLoading(false);return;}setDocuments((data??[]).map(item=>{const client=Array.isArray(item.clients)?item.clients[0]:item.clients;const metadata=item.drive_metadata&&typeof item.drive_metadata==='object'&&!Array.isArray(item.drive_metadata)?item.drive_metadata as Record<string,unknown>:{};return{id:item.id,fileName:item.file_name,url:item.drive_web_view_link,clientName:client?.legal_name??'Cliente',rut:client?.rut??'—',type:item.document_type,inferredType:item.inferred_document_type,source:item.classification_source,path:String(metadata.path??item.file_name),modifiedAt:item.modified_at};}));setLoading(false);};
  useEffect(()=>{void load();},[]);
  const kinds:DocumentKind[]=['f29','f22','rcv','bce','dj_1948','dj_1949','excel','pdf','certificate','receipt','contract','other'];
  const labels:Record<DocumentKind,string>={f29:'F29',f22:'F22',rcv:'RCV',bce:'BCE',dj_1948:'DJ 1948',dj_1949:'DJ 1949',excel:'Excel',pdf:'PDF',certificate:'Certificado',receipt:'Comprobante',contract:'Contrato',other:'Otro'};
  const visible=useMemo(()=>documents.filter(item=>`${item.fileName} ${item.clientName} ${item.rut} ${item.path}`.toLowerCase().includes(query.toLowerCase())&&(type==='all'||item.type===type)),[documents,query,type]);
  const classify=async(item:DocumentRow,next:DocumentKind)=>{setMessage('Guardando clasificación…');try{await classifyDocument(item.id,next);await load();setMessage('Clasificación manual guardada.');}catch(reason){setError(reason instanceof Error?reason.message:'No fue posible clasificar.');}};
  return <div className="control-content wide-content"><div className="control-page-head"><div><span>Archivo indexado</span><h1>Documentos</h1><p>Tipos inferidos por nombre, extensión y ruta; cualquier cambio manual queda distinguido y auditado.</p></div></div>{error&&<div className="control-data-state is-error"><AlertTriangle size={16}/>{error}</div>}{message&&<div className="control-data-state is-success">{message}</div>}<section className="operations-card"><div className="table-toolbar"><div className="toolbar-search"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar archivo, ruta, cliente o RUT…"/></div><select value={type} onChange={event=>setType(event.target.value)}><option value="all">Todos los tipos</option>{kinds.map(value=><option value={value} key={value}>{labels[value]}</option>)}</select></div>{loading?<div className="control-data-state">Cargando documentos…</div>:<div className="table-scroll"><table className="ops-table responsive-table documents-workspace-table"><thead><tr><th>Archivo</th><th>Cliente</th><th>Ruta</th><th>Tipo</th><th>Origen</th><th>Modificado</th><th/></tr></thead><tbody>{visible.map(document=><tr key={document.id}><td data-label="Archivo"><strong className="document-name" title={document.fileName}><FileSpreadsheet size={14}/>{document.fileName}</strong></td><td data-label="Cliente">{document.clientName}<small className="table-secondary">{document.rut}</small></td><td data-label="Ruta"><span className="document-path" title={document.path}>{document.path}</span></td><td data-label="Tipo"><select className="inline-select" value={document.type} onChange={event=>void classify(document,event.target.value as DocumentKind)}>{kinds.map(value=><option value={value} key={value}>{labels[value]}</option>)}</select></td><td data-label="Origen"><span className={`classification-source ${document.source}`}>{document.source==='manual'?'Manual':`Inferido${document.inferredType?` · ${labels[document.inferredType]}`:''}`}</span></td><td data-label="Modificado">{document.modifiedAt?new Intl.DateTimeFormat('es-CL').format(new Date(document.modifiedAt)):'—'}</td><td>{document.url&&<a className="icon-button compact" href={document.url} target="_blank" rel="noreferrer" aria-label="Abrir en Drive"><ExternalLink size={14}/></a>}</td></tr>)}</tbody></table>{!visible.length&&<div className="empty-table"><FolderOpen size={18}/>No se encontraron documentos.</div>}</div>}</section></div>;
}

export function ActivityWorkspace() {
  const [entries, setEntries] = useState<ActivityRow[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { void (async () => { if (!supabase) { setLoading(false); return; } const { data, error: queryError } = await supabase.from('activity_log').select('id,action,entity_type,created_at,clients(legal_name),profiles!activity_log_actor_id_fkey(full_name)').order('created_at', { ascending: false }).limit(300); if (queryError) { setError(queryError.message); setLoading(false); return; } setEntries((data ?? []).map(item => { const client = Array.isArray(item.clients) ? item.clients[0] : item.clients; const profile = Array.isArray(item.profiles) ? item.profiles[0] : item.profiles; return { id: item.id, action: item.action, entityType: item.entity_type, createdAt: item.created_at, clientName: client?.legal_name ?? 'Sistema', actor: profile?.full_name ?? 'Sistema' }; })); setLoading(false); })(); }, []);
  const visible = entries.filter(item => `${item.action} ${item.clientName} ${item.actor}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="control-content wide-content"><div className="control-page-head"><div><span>Auditoría</span><h1>Actividad</h1><p>Registro transversal de cambios operativos, comunicaciones y cobros.</p></div></div>{error && <div className="control-data-state is-error"><AlertTriangle size={16}/>{error}</div>}<section className="operations-card"><div className="table-toolbar"><div className="toolbar-search"><Search size={16}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar acción, cliente o usuario…"/></div></div>{loading ? <div className="control-data-state">Cargando actividad…</div> : <div className="activity-workspace-list">{visible.map(entry => <article key={entry.id}><span><Activity size={14}/></span><div><strong>{entry.action.replaceAll('_', ' ')}</strong><p>{entry.clientName} · {entry.entityType}</p></div><div><strong>{entry.actor}</strong><time>{new Intl.DateTimeFormat('es-CL', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(entry.createdAt))}</time></div></article>)}</div>}</section></div>;
}
